# Generated by Django 3.0.6 on 2020-06-24 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 9, 31, 36, 815345, tzinfo=utc)),
        ),
    ]
