# Generated by Django 3.0.6 on 2020-06-24 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200624_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='arvind', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 9, 40, 16, 959758, tzinfo=utc)),
        ),
    ]
