# Generated by Django 3.0.6 on 2020-06-24 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200624_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='faculty_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 10, 52, 24, 799975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='standerd',
            field=models.CharField(max_length=20),
        ),
    ]
